Algoritmo "semnome"

Var n1, n2, b:real


Inicio
  escreva("digite seu nivel de instrutor: ")
  leia(n1)
  escreva("digite suas horas trabalhadas: ")
  leia(n2)

   se (n1=1)entao
   b<- 15*n2
   escreva("você receberá: ",b)
    fimse
    
     se (n1=2)entao
   b<- 20*n2
   escreva("você receberá: ",b)
    fimse
    
      se (n1=3)entao
   b<- 30*n2
   escreva("você receberá: ",b)
    fimse
    
    
    
    
Fimalgoritmo